// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhZYOFKRaQxJ_W50gbdo5nbFa2yZsXVqY',
    appId: '1:717912287950:web:4dac2cc8eb79f2d5943e9f',
    messagingSenderId: '717912287950',
    projectId: 'skin-b855e',
    authDomain: 'skin-b855e.firebaseapp.com',
    storageBucket: 'skin-b855e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtUIrGXT4UZY3s1y4CTyVEzrxd761wVQg',
    appId: '1:717912287950:android:2879de77303c9e94943e9f',
    messagingSenderId: '717912287950',
    projectId: 'skin-b855e',
    storageBucket: 'skin-b855e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeUZ_D64P9MICrVfRZ7L79a_3T_jhCnI',
    appId: '1:717912287950:ios:2656dcd65eda6b07943e9f',
    messagingSenderId: '717912287950',
    projectId: 'skin-b855e',
    storageBucket: 'skin-b855e.appspot.com',
    iosClientId: '717912287950-dlehrno2vmgbb61972nm9lia9cvpjue5.apps.googleusercontent.com',
    iosBundleId: 'com.example.homePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeUZ_D64P9MICrVfRZ7L79a_3T_jhCnI',
    appId: '1:717912287950:ios:2656dcd65eda6b07943e9f',
    messagingSenderId: '717912287950',
    projectId: 'skin-b855e',
    storageBucket: 'skin-b855e.appspot.com',
    iosClientId: '717912287950-dlehrno2vmgbb61972nm9lia9cvpjue5.apps.googleusercontent.com',
    iosBundleId: 'com.example.homePage',
  );
}
